### ISSUE TITLE
Throw OperationCanceledException exceptions to AppDomain UnhandledException

### ISSUE THREAD

**Issue by czd890** [SumoLogic/sumologic-net-appenders#88]
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at SumoLogic.Logging.Common.Sender.SumoLogicMessageSender.TrySend(String body, String name, String category, String host)
   at SumoLogic.Logging.Common.Sender.SumoLogicMessageSender.Send(String body, String name, String category, String host)
   at SumoLogic.Logging.NLog.BufferedSumoLogicTarget.<InitializeTarget>b__66_0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by snakefoot** [comment]
Created PR #89

**Comment by snakefoot** [comment]
@czd890 Are you using ver. 1.0.1.1 that includes #78 ?

**Comment by czd890** [comment]
I using the SumoLogic.Logging.NLog.1.0.1.1, and decompiler the dll ,included #78 .
#78 Added TaskCanceledException, but not add OperationCanceledException

**Comment by snakefoot** [comment]
Yes also noticed this after writing my comment. The PR #89 will fix the issue


Sent from my Sony Xperia


---- czd890 wrote ----


I using the SumoLogic.Logging.NLog.1.0.1.1, and decompiler the dll ,included #78<https://github.com/SumoLogic/sumologic-net-appenders/pull/78> .
#78<https://github.com/SumoLogic/sumologic-net-appenders/pull/78> Added TaskCanceledException, but not add OperationCanceledException

**Comment by czd890** [comment]
Looking forward to the publish of the new version

**Comment by snakefoot** [comment]
Looks like the project maintainer @bin3377 is bit occupied as there several pending pull requests. Not sure how long you will wait.


Sent from my Sony Xperia


---- czd890 wrote ----


Looking forward to the publish of the new version
